version: "3.9"

services:
  app:
    image: python:3.12-slim  # Usa una imagen de Python
    container_name: my-python-app
    ports:
      - "9000:9000"
    volumes:
      - .:/app  # Mapea el código fuente del host al contenedor
    working_dir: /app  # Establece el directorio de trabajo
    command: uvicorn main:app --host 0.0.0.0 --port 9000  # Comando para ejecutar FastAPI
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: |
      /bin/bash -c "pip install --no-cache-dir -r /app/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 9000"
