version: "3.9"

services:
  app:
    image: python:3.12-slim  # Usa una imagen base de Python
    container_name: my-python-app
    volumes:
      - .:/app  # Mapea el código fuente del host al contenedor
    working_dir: /app  # Establece el directorio de trabajo
    ports:
      - "127.0.0.1:9000:9000"  # Expone el puerto solo a la interfaz local
    environment:
      - PYTHONUNBUFFERED=1  # Evita el almacenamiento en búfer de salida de Python
    entrypoint: |
      /bin/bash -c "
      pip install --upgrade pip &&
      pip install --no-cache-dir -r requirements.txt &&
      uvicorn main:app --host 0.0.0.0 --port 9000"
