name: Deploy Python 3.12 Application

on: [push]

jobs:
  deploy:
    name: Build and Deployment
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Conexión al servidor por SSH
    - name: SSH into the server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Clonar o actualizar el repositorio
          cd /home/microservicio
          git clone https://github.com/Jjalixto/Microservicio-Crear-y-Agendar.git
          
          # Construir y levantar contenedor con Docker Compose
          cd /home/microservicio/Microservicio-Crear-y-Agendar
          python3.12 -m venv myenv
          source myenv/bin/activate
          python3.12 -m pip install -r requirements.txt
          python3.12 -m uvicorn main:app --reload --host 127.0.0.1 --port 9000

