name: Deploy Python 3.12 Application

on: [push]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Conexión al servidor por SSH
    - name: SSH into the server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Clonar o actualizar el repositorio
          cd /home/microservicio
          git clone https://github.com/Jjalixto/Microservicio-Crear-y-Agendar.git
          
          # Construir y levantar contenedor con Docker Compose
          docker-compose down  # Detener cualquier instancia previa
          docker-compose up -d --build

          # Verificar si el contenedor se está ejecutando
          docker ps
