name: Deploy Python 3.12 Application

on: [push]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Conexión al servidor por SSH
    - name: SSH into the server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.NAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |

          echo "TENANT_ID=${{ secrets.TENANT_ID }}" > /home/microservicio/.env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> /home/microservicio/.env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> /home/microservicio/.env
          # Clonar o actualizar el repositorio
          cd /home/microservicio
          git clone https://github.com/Jjalixto/Microservicio-Crear-y-Agendar.git
          
          # Construir y levantar contenedor con Docker Compose
          cd /home/microservicio/Microservicio-Crear-y-Agendar
          docker-compose up -d

          # Verificar si el contenedor se está ejecutando
          docker ps
    # Paso 2: Configuración de variables de entorno para la aplicación
    - name: Set up environment variables
      run: |
        echo "TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV

    # Opcional: Verificar que las variables de entorno estén configuradas
    - name: Check environment variables
      run: |
        echo "TENANT_ID: $TENANT_ID"
        echo "CLIENT_ID: $CLIENT_ID"